version: '3.8'

name: "discord-badzbot"

services:
  bot-db:
    image: mongo
    ports:
      -27700:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456